name: Build Lambda Layer (Python 3.11 via AWS Lambda Base Image)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Lambda Layer using Lambda Python 3.11 Image
        run: |
          mkdir -p layer_output
          docker run --rm --entrypoint /bin/bash -v "$PWD/layer_output:/output" public.ecr.aws/lambda/python:3.11 -c "
            pip install --upgrade pip \
            && mkdir -p /tmp/python \
            && pip install pdfplumber python-docx -t /tmp/python \
            && cd /tmp \
            && zip -r /output/lambda_layer.zip python
          "

      - name: Upload Lambda Layer ZIP
        uses: actions/upload-artifact@v4
        with:
          name: lambda_layer
          path: layer_output/lambda_layer.zip
