name: Build Lambda Layer (Amazon Linux 2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build layer in Amazon Linux 2
        run: |
          mkdir layer_output
          docker run --rm -v "$PWD/layer_output:/output" amazonlinux:2 bash -c "
            yum install -y python3 pip zip gcc gcc-c++ make \
              && pip3 install pdfplumber python-docx -t /output/python \
              && cd /output \
              && zip -r lambda_layer.zip python
          "

      - name: Upload layer zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda_layer
          path: layer_output/lambda_layer.zip
