name: Build Lambda Layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        mkdir -p python
        pip install -r requirements.txt -t python

    - name: Zip layer
      run: zip -r langchain-layer.zip python

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: langchain-layer
        path: langchain-layer.zip
