name: Build Lambda Layer (pdfplumber + python-docx)

on:
  workflow_dispatch:  # lets you trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages to /python folder
        run: |
          mkdir -p layer/python
          pip install pdfplumber python-docx -t layer/python

      - name: Zip layer
        run: |
          cd layer
          zip -r ../lambda_layer.zip .

      - name: Upload Lambda layer zip as artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda_layer
          path: lambda_layer.zip
